Typescript
Allgud/card_pairs pull request #4
Opened 2022-09-14 07:20 UTC by Allgud

В спешке я запутался в ветках. Пуляю уже из следующей. Уже с попыткой использовать ts. Про .gitignore  поздно прочитал, всё добавлю в следующий ПР

2022-09-15 05:56 UTC, mrerberg requested changes

2022-09-15 05:56 UTC, mrerberg commented on src/lib/constants.ts
> +type DiffMap = {
Давай без сокращений. Diff - разница

2022-09-15 05:56 UTC, mrerberg commented on src/lib/constants.ts
> +type MapItem = {
Зачем тебе типы, если ты их не используешь?

2022-09-15 19:07 UTC, Allgud commented on src/lib/constants.ts
> +type DiffMap = {
Здесь поправил.

2022-09-15 19:07 UTC, Allgud commented on src/lib/constants.ts
> +type MapItem = {
Удалил.

2022-09-16 06:45 UTC, mrerberg requested changes

2022-09-16 06:45 UTC, mrerberg commented on src/lib/types.ts
> +export type Cards = {
export type Cards = Card[]

2022-09-16 06:45 UTC, mrerberg commented on src/lib/types.ts
> +export type Template = {
Чей template?

2022-09-16 06:45 UTC, mrerberg commented on src/lib/helpers.ts
> +function createArray(): number[] {
Эта функция называется по одному, а делает немного другое

2022-09-16 06:45 UTC, mrerberg commented on src/lib/Card.ts
> +    card: string | undefined;
card?: string;

2022-09-16 06:45 UTC, mrerberg commented on src/app.js
> +    const timer = new Timer(minutesEl, secondsEl)
При каждом вызове функции `handleTimer` ты создаешь **новый экземпляр класса** таймера. От этого у тебя чистится интервал, только вот не тот

2022-09-16 06:45 UTC, mrerberg commented on src/app.js
> +    const timer = new Timer(minutesEl, secondsEl)
Тебе бы сделать 1 инстанс класса на программу или на страницу

2022-09-17 14:26 UTC, Allgud commented on src/app.js
> +    const timer = new Timer(minutesEl, secondsEl)
Спасибо большое. Сработало))

2022-09-17 14:26 UTC, Allgud commented on src/lib/Card.ts
> +    card: string | undefined;
Поправил.

2022-09-17 14:28 UTC, Allgud commented on src/lib/helpers.ts
> +function createArray(): number[] {
Тоже не понял. Мне нужен массив с цифрами от 1 до 35. Я его генерирую этой функцией. Надо назвать generateArray?

2022-09-17 14:28 UTC, Allgud commented on src/lib/types.ts
> +export type Template = {
Просто template. Все шаблоны построены по одному принципу.

2022-09-17 14:28 UTC, Allgud commented on src/lib/types.ts
> +export type Cards = {
Здесь не понял. Мне надо type Card сделать?

2022-09-18 07:22 UTC, Allgud commented on src/lib/types.ts
> +export type Cards = {
Кажется догнал. Переделал.

2022-09-18 12:35 UTC, mrerberg commented on src/lib/types.ts
> +export type Template = {
Так а шаблон чего? Шаблон не может жить просто сам по себе

2022-09-18 12:39 UTC, mrerberg requested changes

2022-09-18 12:39 UTC, mrerberg commented on src/lib/types.ts
> +export type Cards = {
Не вижу обновления кода

2022-09-18 12:39 UTC, mrerberg commented on src/lib/types.ts
> +    timer?: Function | undefined
timer?: Function

2022-09-18 12:39 UTC, mrerberg commented on src/lib/types.ts
> +export type Template = {
HtmlElementTemplate?

2022-09-18 12:39 UTC, mrerberg commented on src/lib/Timer.ts
> +export default class Timer {
С сокрытием логики таймера в класс это ты хорошо придумал, кстати

2022-09-18 12:39 UTC, mrerberg commented on src/lib/Timer.ts
> +    minEl: HTMLElement;
Я думаю. что можно иметь 1 элемент для вставки времени. Зачем контейнер для секунд?

2022-09-18 12:39 UTC, mrerberg commented on src/lib/Timer.ts
> +    interval: NodeJS.Timer | undefined
interval?: NodeJS.Timer

2022-09-18 12:39 UTC, mrerberg commented on src/app.js
> +        application.timer.start()
В конце if есть смысл сделать return, чтобы выйти из функции досрочно, если мы попали в условие. Дальнейшие if нет смысла проверять

2022-09-22 08:22 UTC, merged