Внёс все изменения
Allgud/card_pairs pull request #5
Opened 2022-09-18 13:12 UTC by Allgud

[Этот пр](https://github.com/Allgud/card_pairs/pull/4) решил закрыть, ибо много уже накопилось. Все изменения внёс, но 2 загвоздки остались.

Не смог перевести на ts файл template-engine.js. Там компилятор ругается вот на этот блок

if (block.attrs) {
        const keys = Object.keys(block.attrs)

        keys.forEach((key) => {
            element.setAttribute(key, block.attrs[key])
   })
Я честно уже просто не знаю куда копать.

И в HtmlElementTemplate в одном месте использовал тип any.
Иначе вот на эту конструкцию ругается 

    template.content[0].content[0].attrs = {
        src: props.src,
        alt: props.alt,
    }
    template.content[0].content[1].content = props.content
    template.content[0].content[2].content[1].content = time
Тоже так и не понял как это обойти

2022-09-19 07:03 UTC, mrerberg commented
А что за ошибка то вылезает?

2022-09-19 07:03 UTC, mrerberg requested changes

2022-09-19 07:03 UTC, mrerberg commented on src/lib/constants.ts
> +    'win': {
Можно без кавычек

2022-09-19 07:03 UTC, mrerberg commented on src/lib/helpers.ts
> +const cardsCount: number = 36
это программная константа, поэтому CARDS_COUNT. Еще лучше 
```
const MAX_CARDS_COUNT = 36 as const
```

2022-09-19 07:03 UTC, mrerberg commented on src/lib/types.ts
> +    content: any
А что в идеале сюда должно приходить? Или какие варианты? Можно оставить any, если совсем туго с типизацией

2022-09-19 09:23 UTC, Allgud commented on src/lib/types.ts
> +    content: any
В идеале там массив с таким же HtmlElementTemplate или строка. Но даже такая конструкция Array<HtmlElementTemplate> не помогает. Редактор говорит, что свойство content нельзя добавить в тип string | HtmlElementTemplate[].

2022-09-19 09:25 UTC, Allgud commented on src/lib/helpers.ts
> +const cardsCount: number = 36
Думал об этом. Вообще хотел все переменные из constants.ts так переименовать.

2022-09-19 16:32 UTC, Allgud commented on src/lib/constants.ts
> +    'win': {
Поправил

2022-09-19 16:42 UTC, Allgud commented
> А что за ошибка то вылезает?

Не совсем понял про какую ошибку мы сейчас, но предположил, что про ошибку в моём описании.
![Снимок экрана (159)](https://user-images.githubusercontent.com/70888212/191069139-58ca83d2-2e68-4787-8061-bea4a591e136.png)

2022-09-19 18:17 UTC, mrerberg commented
> > А что за ошибка то вылезает?
> 
> Не совсем понял про какую ошибку мы сейчас, но предположил, что про ошибку в моём описании. ![Снимок экрана (159)](https://user-images.githubusercontent.com/70888212/191069139-58ca83d2-2e68-4787-8061-bea4a591e136.png)
> 
> И если с верхней ошибкой я примерно знаю что делать, то с нижней вообще ума не приложу.

Вместо `.keys` воспользуйся `.entries`, так ты получишь и ключ и значение. ТС немного с ума сошел, проблема в том, что он считает key строкой, а attrs имеет интерфейс с конкретным (константным) числом ключей

2022-09-19 18:18 UTC, mrerberg requested changes

2022-09-19 18:18 UTC, mrerberg commented on src/lib/types.ts
> +    content: any
Может подойдет ?

```ts
content: string | HTMLElement | HTMLElement[]
```

2022-09-20 16:20 UTC, Allgud commented on src/lib/types.ts
> +    content: any
> Может подойдет ?

Не подошло. 


![Снимок экрана (160)](https://user-images.githubusercontent.com/70888212/191311703-7a3f32aa-12ca-4542-b6d5-4cedef4445c0.png)

2022-09-20 16:25 UTC, Allgud commented on src/lib/types.ts
> +    content: any
Не, не подошло.

![Снимок экрана (160)](https://user-images.githubusercontent.com/70888212/191312750-e3c978cc-8f4d-4f64-871d-8fd39cd38ac7.png)

2022-09-21 06:21 UTC, mrerberg requested changes

2022-09-21 06:21 UTC, mrerberg commented on src/lib/template-engine.ts
> +            element.setAttribute(key, block.attrs ? block.attrs[key] : '')
element.setAttribute(key, value)

2022-09-22 08:22 UTC, merged